# Generated by Django 4.2.13 on 2024-05-22 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrteam',
            name='employee_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_details', to='ctc.hrteam'),
        ),
    ]
